name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true # Ensures the built image is loaded into the host's Docker daemon
          tags: health-app-demo:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy Application
        run: |
          echo "Stopping old container..."
          docker stop health-app-demo-container || true
          
          echo "Removing old container..."
          docker rm health-app-demo-container || true
          
          echo "Starting new container..."
          docker run -d --restart unless-stopped --name health-app-demo-container -p 4173:4173 health-app-demo:latest
